### ISSUE TITLE
works only 1 day

### ISSUE THREAD

**Issue by tutumeme** [rastaayoub/BCHCLICKBOT#1]
yeah, i manged to run bot perfectly i have run 3 bot on different accounts all 3 met the same fate:after 1 day they all had the same error;also i can run the bot after 1 day when timer ends (i can complete task mannualy so why  set 1 day timer?plz just remove that timer,make it like 5 min,its taking whole day which is so inconviniet(sorry for grammer)
![Screenshot (14)](https://user-images.githubusercontent.com/62719288/77809757-2b89d200-70b7-11ea-93e1-312b4bc224e7.png)
ERROR:telethon.client.updates:Unhandled exception on EVENTER
Traceback (most recent call last):
  File "C:\Users\Kingo dude\AppData\Local\Programs\Python\Python38\lib\site-packages\telethon\client\updates.py", line 428, in _dispatch_update
    await callback(event)
  File "bb.py", line 220, in EVENTER
    await boter()
  File "bb.py", line 146, in boter
    await PROFILER(StartBotRequest(bot=botUN,peer=botUN,start_param=startID))
  File "C:\Users\Kingo dude\AppData\Local\Programs\Python\Python38\lib\site-packages\telethon\client\users.py", line 34, in __call__
    await r.resolve(self, utils)
  File "C:\Users\Kingo dude\AppData\Local\Programs\Python\Python38\lib\site-packages\telethon\tl\functions\messages.py", line 4540, in resolve
    self.bot = utils.get_input_user(await client.get_input_entity(self.bot))
  File "C:\Users\Kingo dude\AppData\Local\Programs\Python\Python38\lib\site-packages\telethon\client\users.py", line 404, in get_input_entity
    await self._get_entity_from_string(peer))
  File "C:\Users\Kingo dude\AppData\Local\Programs\Python\Python38\lib\site-packages\telethon\client\users.py", line 516, in _get_entity_from_string
    result = await self(
  File "C:\Users\Kingo dude\AppData\Local\Programs\Python\Python38\lib\site-packages\telethon\client\users.py", line 74, in __call__
    result = await future
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 35642 seconds is required (caused by ResolveUsernameRequest)

**Comment by tutumeme** [comment]
bot manages to start but some error generates and places the timer ,after the timer ends ,the timer resets itself ,plz resolve the issue

**Comment by rastaayoub** [comment]
this error is a telegram api block . it is not a problem in the bot .
