### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rows'

### ISSUE THREAD

**Issue by metapodcod** [rastaayoub/BCHCLICKBOT#3]
some missions pass without ever doing

```
ERROR:telethon.client.updates:Unhandled exception on EVENTER
Traceback (most recent call last):
  File "C:\Users\metapodcod\Documents\BCHCLICKBOT\venv\lib\site-packages\telethon\client\updates.py", line 451, in _dispatch_update
    await callback(event)
  File "C:\Users\metapodcod\Documents\BCHCLICKBOT\LTC.py", line 334, in EVENTER
    await boter()
  File "C:\Users\metapodcod\Documents\BCHCLICKBOT\LTC.py", line 182, in boter
    msms = mssag[0].reply_markup.rows[0].buttons[0].url
AttributeError: 'NoneType' object has no attribute 'rows'
```

**Comment by metapodcod** [comment]
I got another error today
```
[ERROR/2020-12-28 08:25:06,755] telethon.client.updates: Unhandled exception on EVENTER
Traceback (most recent call last):
  File "C:\Users\metapodcod\Documents\BCHCLICKBOT\venv\lib\site-packages\telethon\client\updates.py", line 451, in _dispatch_update
    await callback(event)
  File "C:\Users\metapodcod\Documents\BCHCLICKBOT\LTC.py", line 293, in EVENTER
    papa = await event.client(ResolveUsernameRequest(username))
  File "C:\Users\metapodcod\Documents\BCHCLICKBOT\venv\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\metapodcod\Documents\BCHCLICKBOT\venv\lib\site-packages\telethon\client\users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.UsernameInvalidError: Nobody is using this username, or the username is unacceptable. If the latter, it must match r"[a-zA-Z][\w\d]{3,30}[a-zA-Z\d]" (caused by ResolveUsernameRequest)

```
